### ISSUE TITLE
Security Implications on RFC-0001 Block Time Smoothing

### ISSUE THREAD

**Issue by sunnyking** [peercoin/rfcs#1]
As discussed in last meeting,
0001 must be evaluated over these categories of security considerations:
a) Full blockchain control
b) Multiple-block reorg
c) Single-block reorg
I will give a limited analysis over c) single-block reorg.
The proposal understands that the block trust score used for reorg must be the adjusted difficulty based on stake time difference. This makes competing blocks have different trust scores, up to 10x. Note currently peercoin competing blocks have exactly the same difficulty.
When difficulty varies between competing blocks, it is quite easy to perform single block reorganization attack. When an attacker finds a block, he could wait until a competing block shows up in the network, then releases his own to force a single-block reorg.
This could potentially mean up to a majority of single block confirmations cannot be trusted under the current proposal.

**Comment by hrobeers** [comment]
Thanks for enumerating your security considerations.

About the single block reorg, I don't see how it makes single block confirmations less secure.
If a block is produced at 10x the difficulty, the same stake in the current system would have a similar chance of producing multiple blocks offline surpassing the block trust by the same amount.
So as far as I understand, the security of a one block confirmation remains unchanged.

**Comment by hrobeers** [comment]
RFC rejected
