### ISSUE TITLE
#0005 Unspendable Zero Outputs

### ISSUE THREAD

**Issue by hrobeers** [peercoin/rfcs#6]
To be discussed.

**Comment by youngpascal** [comment]
[RFC #0005](https://github.com/peercoin/rfcs/blob/master/text/0005-unspendable-zero-outputs/0005-unspendable-zero-outputs.md)

**Comment by d5000** [comment]
Support, seems reasonable. However, I would trash the 0.01 requirement entirely, but I understand that this would change the anti-spam model.

**Comment by nohea** [comment]
Well, i don't have any zero-value outputs i want to spend ;-) 
And i don't want my node to use more memory on it. 
Plus, i would rather do that first before trying to replace UTXO tables with other tech implementations.

**Comment by Nagalim** [comment]
Zero-value outputs are useful for pt2h and other tagging-like protocols.  They are no more useful as spendable outputs than they are as unspendable ones, as spending a UTXO takes more data than simply tagging a new one.  For these reasons, I am for allowing zero outputs but making them unspendable.
